channels:
- conda-forge
dependencies:
#- python=3.8
# mapping
- basemap
- basemap-data-hires
- numba
# data
- xarray
- h5netcdf
#- netcdf4 
- s3fs
# - dask
# - statsmodels
# hysplit
#- geopy
# atmpy
# - timezonefinder
# - ephem
# - python-pptx
# - pysolar
#satellite retrievals
# - pyquery
