#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 29 09:37:56 2022

@author: hagen

Done:
    DSR

from start to present ... running:
    COD (nimbus 2)
    ACM (pulsar 3q)
    ADP (telg)
    CTP
    
"""


import nesdis_aws
import nesdis_gml_synergy.satlab as ngs
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.surfrad.surfrad as surfrad
import pathlib as pl
import warnings
import socket
import argparse



warnings.filterwarnings("ignore", message="Degrees of freedom <= 0 for slice.")

stations = surfrad.network.stations

# CPEX spring 2020
# start='2020-03-01 00:00:00',
# end='2020-06-01 00:00:00',
#
# CPEX original
# start='2018-08-01 00:00:00',
# end='2018-11-01 00:00:00',


#### COD
def processCOD(path2log = None, 
               start='2017-06-09 00:00:00',
               end='2023-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    print('start', flush = True)
    product = 'COD'
    # alt_var = 'BCM'# None, if the varialbe name is not equal to product name
    path2processed = f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_daytime_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start = start,
                                            end =   end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_daytime_projected2surfrad',
                                                           path2processed = path2processed),
                                            # keep_files=True
                                            verbose = verbose
                                          )
    
    # pl.Path(f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}').mkdir()
    # pl.Path(path2processed).mkdir()
    # 100 lines takes about 50 min
    # sys.stdout.flush()
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '')
    print('done', flush = True)
    return
    
#### ACM
def processACM(path2log = None, 
               start='2017-04-20 13:00:00',
               end='2023-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    product = 'ACM'
    path2processed =  f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start=start,
                                            end=end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_projected2surfrad',
                                                           path2processed = path2processed,
                                                            )
                                            # keep_files=True
                                          )
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '')
    print('done', flush = True)
    return

#### ADP
def processADP(path2log = None, 
               start='2019-12-04 00:00:00',
               end='2021-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    product = 'ADP'
    path2processed =  f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start=start,
                                            end=end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_projected2surfrad',
                                                           path2processed = path2processed,
                                                            )
                                            # keep_files=True
                                          )
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '',
                           verbose = True)
    print('done', flush = True)
    return

#### DSR
def processDSR(path2log = None, 
               start='2019-12-06 00:00:00',
               end='2021-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    """
    Parameters
    ----------
    path2log : TYPE, optional
        DESCRIPTION. The default is None.
    start : TYPE, optional
        DESCRIPTION. The default is '2019-12-06 00:00:00' which is the date DSR became available for GOES 16.
    end : TYPE, optional
        DESCRIPTION. The default is '2021-01-01 00:00:00'.
    no_of_cpu : TYPE, optional
        DESCRIPTION. The default is 1.

    Returns
    -------
    None.

    """
    product = 'DSR'
    path2processed =  f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start=start,
                                            end=end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_projected2surfrad',
                                                           path2processed = path2processed,
                                                            )
                                            # keep_files=True
                                          )
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '')
    print('done', flush = True)
    return

#### ACHA
def processACHA(path2log = None,
               start='2019-12-03 00:00:00',
               end='2021-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    product = 'ACHA'
    path2processed =  f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start=start,
                                            end=end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_projected2surfrad',
                                                           path2processed = path2processed,
                                                            )
                                            # keep_files=True
                                          )
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '')
    print('done', flush = True)
    return

#### CTP
def processCTP(path2log = None, 
               start='2017-05-17 00:00:00',
               end='2021-01-01 00:00:00',
               no_of_cpu = 1,
               verbose = False):
    product = 'CTP'
    path2processed =  f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}_projected2surfrad/'
    query = nesdis_aws.nesdis_aws.AwsQuery(
                                            path2folder_local=f'/nfs/stu3data2/Satellite_data/goes/16/ABI_L2_{product}/',
                                            satellite='16',
                                            product=f'ABI-L2-{product}',
                                            scan_sector='C',
                                            start=start,
                                            end=end,
                                            process = dict(#concatenate = 'daily',
                                                           function = lambda row: ngs.projection_function_multi(row), #,, alt_var),
                                                           prefix = f'ABI_L2_{product}_projected2surfrad',
                                                           path2processed = path2processed,
                                                            )
                                            # keep_files=True
                                          )
    print('make workplan', flush = True)
    print(f'workplan.shape: {query.workplan.shape}', flush = True)
    # sys.stdout.flush()
    query.process_parallel(no_of_cpu = no_of_cpu, 
                           process_function=ngs.projection_function_multi, args={'stations': stations}, 
                           path2log = path2log, 
                           subprocess = product,
                           server = socket.gethostname(),
                           comment = '')
    print('done', flush = True)
    return

#### if __name__ == '__main__':
if __name__ == '__main__':
    #### argparsing
    parser = argparse.ArgumentParser()
    parser.add_argument('-n', '--todo', nargs='+', default=[], help = 'list of processes to run. To see option type jibarish here read the error message')
    parser.add_argument('-c', '--cpus', help = 'number of cpus')
    parser.add_argument('-s', '--start', help = 'start datetime, e.g. "2022-01-01 00:00:00"')
    parser.add_argument('-e', '--end', help = 'end datetime, e.g. "2022-01-01 00:00:00"')
    parser.add_argument('-v', '--verbose', help = 'verbose', action='store_true')
    # parser.add_argument('-t', '--test', action="store_true", help='will not execute at the end.')
    # parser.add_argument('-c', '--comment', help = 'some comment, e.g. which server this was stared on')
    args = parser.parse_args()
    print('args:')
    print(args)
    
    todo_all = [{'name':'COD', 'target':processCOD},
                {'name':'ACM', 'target':processACM},
                {'name':'ADP', 'target':processADP},
                {'name':'DSR', 'target':processDSR},
                {'name':'ACHA', 'target':processACHA},
                {'name':'CTP', 'target':processCTP},
                ]
    
    todo = [td for td in todo_all if td['name'] in args.todo]
    todo_invalid = [td for td in args.todo if td not in [td['name'] for td in todo_all]]
    assert(len(todo_invalid) == 0), f'The processes {todo_invalid} are no valid options. Choose from:\n{[td["name"] for td in todo_all]}'
    assert(len(todo) > 0), f'No valid process found. Set -n to at least one of the following options:\n{[td["name"] for td in todo_all]}'
    assert(len(todo) == len(args.todo)), 'this should not be possible'#f'Number of valid process ({len(todo)}) not equal to number of provided todo list ({len(args.todo)}). Make sure all your choises are in the available list of processes:\n{[td["name"] for td in todo_all]}' 

    print(f'process to be persued:\n{[td["name"] for td in todo]}')
    
    #### create log file
    fnlog = pl.Path('/home/grad/htelg/.processlogs/goes_aws_scraper_surfrad.log')
    if not fnlog.is_file():
        with open(fnlog, 'w') as log_out:
            log_out.write('datetime,run_status,error,success,warning,subprocess,server,comment\n')
    

    for do in todo:
        do['target'](path2log = fnlog, no_of_cpu = int(args.cpus), start = args.start, end = args.end, verbose = args.verbose)
            
            # (path2log = fnlog)
    # processACM(path2log = fnlog)